[package]
name = "proc-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "2.0.48"
quote = "1.0.35"
heck = "0.5.0"
itertools = { workspace = true }
proc-macro2 = "1.0"
