[package]
name = "starsector_mod_manager"
version = "0.6.2"
authors = ["ikl"]
edition = "2018"
description = "A mod manager for the game Starsector"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = { git = "https://github.com/atlanticaccent/druid", rev = "76c130799d5341d11880b14b95a214dacf537fc3" }
druid-widget-nursery = { git = "https://github.com/atlanticaccent/druid-widget-nursery", rev = "79b5368c26b5badd570959622a15834580ac7931", features = ["material-icons"] }
infer = "0.3.4"
tokio = { version = "1.6.0", features = ["fs", "io-util", "rt-multi-thread", "process"] }
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0"
json5 = "0.3.0"
json_comments = "0.1.0"
if_chain = "1.0.1"
reqwest = { version = "0.11.7", default-features = false, features = ["rustls-tls", "json"]}
serde-aux = "2.1.1"
handwritten-json = { git = "https://github.com/atlanticaccent/rust-handwritten-json.git" }
unrar = "0.4.4"
opener = "0.5"
directories = "3.0"
tempfile = "^3.2"
compress-tools = { git = "https://github.com/OSSystems/compress-tools-rs.git" }
snafu = "^0.6.10"
remove_dir_all = "^0.7.0"
sublime_fuzzy = "0.7.0"
classfile-parser = "~0.3"
zip = "^0.5"
regex = "1.5"
lazy_static = "1.4"
rfd = "0.6.3"
strum = "0.23"
strum_macros = "0.23"
tap = "1.0.1"
rayon = "1.5"
self_update = { version = "0.29.0", default-features = false, features = ["rustls"] }
indexmap = "1.8.0"
chrono = "0.4.19"
wry = { git = "https://github.com/atlanticaccent/wry.git", branch = "events-fork" }
clap = { version = "3.1.6", features = ["derive"] }
interprocess = "1.1.1"
bincode = "1.3.3"

[patch.crates-io]
cairo-rs = { git = "https://github.com/gtk-rs/gtk-rs-core.git", tag = "0.15.1" }
cairo-sys-rs = { git = "https://github.com/gtk-rs/gtk-rs-core.git", tag = "0.15.1" }
gdk-sys = { git = "https://github.com/gtk-rs/gtk3-rs.git", tag = "0.15.1" }
# gtk = { git = "https://github.com/gtk-rs/gtk3-rs.git", tag = "0.15.1" }
glib-sys = { git = "https://github.com/gtk-rs/gtk-rs-core.git", tag = "0.15.1" }
# gtk-sys = { git = "https://github.com/gtk-rs/gtk3-rs.git", tag = "0.15.1" }

[package.metadata.bundle]
name = "Starsector Mod Manager"
id = "org.laird.starsector_mod_manager"
osx_minimum_system_version = "10.10"
