[package]
name = "starsector_mod_manager"
version = "0.7.2"
authors = ["ikl"]
edition = "2018"
description = "A mod manager for the game Starsector"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = { git = "https://github.com/atlanticaccent/druid", branch = "update-gtk", default-features = false, features = ["im", "serde", "x11"] }
druid-widget-nursery = { path = "../druid-widget-nursery", default-features = false, features = ["material-icons", "async"] }
infer = "0.3.4"
tokio = { version = "1.6.0", features = ["fs", "io-util", "rt-multi-thread", "process", "macros"] }
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0"
json5 = "0.3.0"
json_comments = "0.1.0"
reqwest = { version = "0.11.7", default-features = false, features = ["rustls-tls", "json"]}
serde-aux = "2.1.1"
handwritten-json = { git = "https://github.com/atlanticaccent/rust-handwritten-json.git" }
unrar = "0.4.4"
opener = "0.5"
directories = "3.0"
tempfile = "^3.2"
compress-tools = "0.14.1"
snafu = "^0.6.10"
remove_dir_all = "^0.7.0"
sublime_fuzzy = "0.7.0"
classfile-parser = "~0.3"
zip = "^0.5"
regex = "1.5"
lazy_static = "1.4"
strum = "0.23"
strum_macros = "0.23"
tap = "1.0.1"
rayon = "1.5"
self_update = { version = "0.29.0", default-features = false, features = ["rustls"] }
indexmap = "1.8.0"
chrono = { version = "0.4.19", features = ["serde"] }
clap = { version = "3.1.6", features = ["derive"] }
interprocess = { git = "https://github.com/kotauskas/interprocess", rev = "5a16b3a" }
bincode = "1.3.3"
rand = "0.8.5"
base64 = "0.13.0"
const_format = "0.2.22"
anyhow = "1.0.57"
junction = "0.2.0"
flate2 = "1.0"
tar = "0.4"
deunicode = "1.3.2"
xxhash-rust = { version = "0.8.6", features = ["xxh3"] }

[target.'cfg(target_os = "linux")'.dependencies]
native-dialog = "0.6.3"

[target.'cfg(not(target_os = "linux"))'.dependencies]
rfd = "0.12.1"

[dependencies.webview-subsystem]
path = "./webview-subsystem"

[dependencies.webview-shared]
path = "./webview-subsystem-shared"

[package.metadata.bundle]
name = "Starsector Mod Manager"
id = "org.laird.starsector_mod_manager"
osx_minimum_system_version = "10.10"

[package.metadata.vcpkg]
git = "https://github.com/microsoft/vcpkg"
rev = "69efe9cc2df0015f0bb2d37d55acde4a75c9a25b"
dependencies = ["libarchive"]

[workspace]
members = [
  "webview-subsystem",
  "webview-subsystem-shared"
]

[profile.dev.package."*"]
opt-level = 3
