[package]
name = "starsector_mod_manager"
version = "0.1.0"
authors = ["ikl"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
infer = "0.3.4"
tokio = { version = "1.6.0", features = ["fs", "io-util"] }
iced = { version = "0.3.0", features = ["glow", "tokio"] }
iced_native ="0.4"
native-dialog = "0.5.5"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0"
json5 = "0.3.0"
json_comments = "0.1.0"
if_chain = "1.0.1"
reqwest = "0.11.3"
serde-aux = "2.1.1"
handwritten-json = { git = "https://github.com/atlanticaccent/rust-handwritten-json.git" }
debug_print = "1.0.0"

[target.'cfg(unix)'.dependencies]
compress-tools = "0.11.1"

[target.'cfg(not(unix))'.dependencies]
zip = "0.5.9"
unrar = "0.4.4"
