[package]
name = "starsector_mod_manager"
version = "0.1.0"
authors = ["ikl"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.5.9"
unrar = "0.4.4"
infer = "0.3.4"
iced = { version = "0.2.0", features = ["glow"] }
iced_native ="0.3"
native-dialog = "0.5.2"
serde_json = "1.0"
json5 = "0.3.0"
json_comments = "0.1.0"
if_chain = "1.0.1"

[target.'cfg(unix)'.dependencies]
compress-tools = "0.11.1"
