[package]
name = "starsector_mod_manager"
version = "0.3.0"
authors = ["ikl"]
edition = "2018"
description = "A mod manager for the game Starsector"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
infer = "0.3.4"
tokio = { version = "1.6.0", features = ["fs", "io-util", "rt"] }
iced = { version = "0.3.0", features = ["glow", "tokio"] }
iced_native ="0.4"
tinyfiledialogs = "^3.8.3"
iced_futures = "0.3"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0"
json5 = "0.3.0"
json_comments = "0.1.0"
if_chain = "1.0.1"
reqwest = { version = "0.11.3", default-features = false, features = ["rustls-tls", "json"]}
serde-aux = "2.1.1"
handwritten-json = { git = "https://github.com/atlanticaccent/rust-handwritten-json.git" }
zip = "0.5.9"
unrar = "0.4.4"
opener = "0.5"
directories = "3.0"

[target.'cfg(target_os = "linux")'.dependencies]
compress-tools = "0.11.1"

[package.metadata.bundle]
name = "Starsector Mod Manager"
id = "org.laird.starsector_mod_manager"
