[package]
name = "starsector_mod_manager"
version = "0.5.2"
authors = ["ikl"]
edition = "2018"
description = "A mod manager for the game Starsector"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
infer = "0.3.4"
tokio = { version = "1.6.0", features = ["fs", "io-util", "rt"] }
iced = { version = "0.3.0", features = ["glow", "tokio"] }
iced_native = "0.4"
iced_aw = { git = "https://github.com/iced-rs/iced_aw", branch = "main", default-features = false, features = ["modal", "card"] }
tinyfiledialogs = "^3.8.3"
native-dialog = "0.5.5"
iced_futures = "0.3"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0"
json5 = "0.3.0"
json_comments = "0.1.0"
if_chain = "1.0.1"
reqwest = { version = "0.11.7", default-features = false, features = ["rustls-tls", "json"]}
serde-aux = "2.1.1"
handwritten-json = { git = "https://github.com/atlanticaccent/rust-handwritten-json.git" }
unrar = "0.4.4"
opener = "0.5"
directories = "3.0"
tempfile = "^3.2"
compress-tools = { git = "https://github.com/OSSystems/compress-tools-rs.git" }
snafu = "^0.6.10"
remove_dir_all = "^0.7.0"
sublime_fuzzy = "0.7.0"
classfile-parser = "~0.3"
zip = "^0.5"
regex = "1.5"
lazy_static = "1.4"

[package.metadata.bundle]
name = "Starsector Mod Manager"
id = "org.laird.starsector_mod_manager"
osx_minimum_system_version = "10.10"
