tab_spaces = 2

unstable_features = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
imports_layout="Mixed"
overflow_delimited_expr=true
wrap_comments = true
format_strings = true
space_after_colon=true
