[build]
rustflags = ["-Z", "threads=16"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-Z", "threads=16", "-C", "target-feature=+crt-static"]
linker = "rust-lld.exe"

[alias]
fast = ["r", "-q", "--manifest-path", "fast/Cargo.toml", "--"]
fast_check = ["r", "-q", "--manifest-path", "fast/Cargo.toml", "--", "check"]
