[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static", "-Zthreads=0"]

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static"]
linker = "rust-lld.exe"
