name: Check Bump on Version

on:
  pull_request:
    branches:
      - release

jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: git fetch --all --tags

      - name: Check Release Version
        uses: thebongy/version-check@v1
        with:
          file: Cargo.toml
          tagFormat: ${version}
          failBuild: true
        id: version_check
      - name:
        run: |
          echo "Version ${{steps.version_check.outputs.releaseVersion}}"
