name: Check Bump on Version

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: git fetch --all --tags

      - name: Get package version
        run: |
          echo "PACKAGE_VERSION=$(cargo pkgid | cut -d# -f2 | cut -d: -f2)" >> $GITHUB_ENV

      - name: Get current tag
        run: |
          echo "TAG_VERSION=$(git describe --tags)" >> $GITHUB_ENV

      - name: Fail if version not equal
        if: env.PACKAGE_VERSION != env.TAG_VERSION
        run: exit 1

      - name: Print detected version
        run: |
          echo "Version ${{ env.PACKAGE_VERSION }}"
