name: Build-Linux-Dynamic

on:
  push:
    branches:
      - release
    tags:
      - '*'
  pull_request:
    branches:
      - release
      - master
  workflow_dispatch:

jobs:
  build:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: sudo apt-get update; sudo apt-get install libarchive-dev libgtk-3-dev webkit2gtk-4.0 libgtksourceview-3.0-dev libayatana-appindicator3-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - name: Check cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --no-fail-fast -- --nocapture
      - uses: actions/upload-artifact@v2
        with:
          name: linux_dynamic
          path: target/release/starsector_mod_manager
