name: Build-Linux-Static

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release

jobs:
  build:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: sudo apt-get update; sudo apt-get install libarchive-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions/upload-artifact@v2
        with:
          name: binary
          path: target/release/starsector_mod_manager