name: Build-Linux-Static

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release
  workflow_dispatch:

jobs:
  build:
    name: Rust project
    runs-on: ubuntu-latest
    env:
      PKG_CONFIG_ALLOW_CROSS: 1
    steps:
      - name: Install Dependencies
        run: sudo apt-get update; sudo apt-get install libarchive-dev musl-tools
      - name: Link g++ to musl-g++
        run: sudo ln -s /bin/g++ /bin/musl-g++
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=x86_64-unknown-linux-musl
      - uses: actions/upload-artifact@v2
        with:
          name: binary
          path: target/x86_64-unknown-linux-musl/release/starsector_mod_manager
