name: Build-macOS

on:
  push:
    branches:
      - release
    tags:
      - "*"
  pull_request:
    branches:
      - release
      - master
  workflow_dispatch:

jobs:
  build:
    name: Rust project
    runs-on: macos-latest
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
      MACOSX_DEPLOYMENT_TARGET: "10.10"
    steps:
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.6

      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install coreutils
          brew install pkgconfig
          brew install libarchive
          echo PKG_CONFIG_PATH=$(brew ls libarchive | grep .pc$ | sed 's|/libarchive.pc||') >> $GITHUB_ENV

      - uses: r7kamura/rust-problem-matchers@v1
      - name: Build
        run: cargo build --release
      - name: Test
        run: cargo test --release --no-fail-fast -- --nocapture

      - name: Install cargo-packager
        run: (cargo install cargo-packager || true)
      - name: Run cargo-packager
        run: cargo packager --release --formats app

      - name: Run bundle-dylibs.sh
        run: ./scripts/bundle-dylibs.sh target/release/moss.app
      - name: Re-sign libs
        run: codesign --force -s - target/release/moss.app/Contents/Frameworks/*

      - uses: actions/upload-artifact@v4
        with:
          name: macos
          path: |
            target/release/moss
            target/release/moss.app
