name: Build-macOS

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release

jobs:
  build:
    name: Rust project
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions/upload-artifact@v2
        with:
          name: binary
          path: target/release/