name: Build-macOS

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release
  workflow_dispatch:

jobs:
  build:
    name: Rust project
    runs-on: macos-latest
    steps:
      - name: Install dependencies
        run: |
          brew install coreutils
          brew install pkgconfig
          brew install libarchive
          echo PKG_CONFIG_PATH="/usr/local/opt/libarchive/lib/pkgconfig" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          minimal: true
      - name: Check cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install cargo-bundle
        run: (cargo install cargo-bundle || true)
      - name: Emit target macOS version env variable
        run: echo MACOSX_DEPLOYMENT_TARGET=10.10 >> $GITHUB_ENV
      - name: Run cargo-bundle
        run: cargo bundle --release
      - name: Run make_portable.sh
        run: ./scripts/make_portable.sh target/release/bundle/osx/Starsector\ Mod\ Manager.app/Contents/MacOS/starsector_mod_manager ../Resources
        shell: bash
      - uses: actions/upload-artifact@v2
        with:
          name: macos
          path: |
            target/release/starsector_mod_manager
            target/release/bundle/osx/Starsector Mod Manager.app