name: Build-macOS

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release
  workflow_dispatch:

jobs:
  build:
    name: Rust project
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install cargo-bundle
        run: cargo install cargo-bundle
      - name: Run cargo-bundle
        run: cargo bundle --release
      - uses: actions/upload-artifact@v2
        with:
          name: macos
          path: |
            target/release/starsector_mod_manager
            target/release/bundle/osx/Starsector Mod Manager.app