name: Build-Windows-Static-Debug

on:
  workflow_dispatch:

jobs:
  build:
    name: Rust project
    runs-on: windows-latest
    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows-static
      VCPKG_ROOT: 'C:\vcpkg'
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
      CARGO_INCREMENTAL: 0
    steps:
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.6

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup vcpkg cache
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: b322364f06308bdd24823f9d8f03fe0cc86fd46f

      - name: Setup vcpkg
        run: |
          (cargo install cargo-vcpkg || true)
          cargo vcpkg build --manifest-path .\moss\Cargo.toml

      - name: Build
        env:
          CARGO_PROFILE_RELEASE_DEBUG_ASSERTIONS: true
        run: cargo build --release
      - name: Test
        run: cargo test --release --features="leaky-api" -- --nocapture

      - uses: actions/upload-artifact@v4
        with:
          name: windows
          path: target/release/moss.exe
