name: Build-Windows-Static

on:
  push:
    branches:
      - release
    tags:
      - "*"
  pull_request:
    branches:
      - release
      - master
  workflow_dispatch:

jobs:
  build:
    name: Rust project
    runs-on: windows-latest
    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows-static
      VCPKG_ROOT: 'C:\vcpkg'
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.6

      - uses: actions/checkout@v4

      - name: Setup vcpkg cache
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 64ca152891d6ab135c6c27881e7eb0ac2fa15bba

      - name: Setup vcpkg
        run: |
          (cargo install cargo-vcpkg || true)
          cargo vcpkg --verbose build --manifest-path .\moss\Cargo.toml

      - name: Build
        run: cargo build --release
      - name: Test
        run: cargo test --release --no-fail-fast --features="leaky-api" -- --nocapture

      - uses: actions/upload-artifact@v4
        with:
          name: windows
          path: target/release/moss.exe
