name: Build-Windows-Static

on:
  push:
    branches:
      - release
    tags:
      - '*'
  pull_request:
    branches:
      - release
      - master
  workflow_dispatch:

jobs:
  build:
    name: Rust project
    runs-on: windows-latest
    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows-static
    steps:
      - uses: actions/checkout@v2

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@main
        id: runvcpkg
        with:
          # This specifies the location of vcpkg, where it is going to be restored from cache, or create from scratch.
          vcpkgDirectory: '${{ runner.workspace }}/vcpkg'

      - name: Install dependencies Windows
        run: ${{ runner.workspace }}/vcpkg integrate install; ${{ runner.workspace }}/vcpkg install libarchive:x64-windows-static
        env:
          VCPKG_ROOT: 'C:\vcpkg'

      - name: Check cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Test
        uses: actions-rs/cargo@v1
        timeout-minutes: 10
        with:
          command: test
          args: --release --no-fail-fast -- --nocapture
      - uses: actions/upload-artifact@v2
        with:
          name: windows
          path: target/release/starsector_mod_manager.exe
