name: Build-Windows-Static-Debug

on:
  workflow_dispatch:

jobs:
  build:
    name: Debug
    runs-on: windows-latest
    steps:
      - run: echo $env:WIX
      - name: Fix WIX path
        env:
          WIX: ${{ env.wix }}
        run: echo "$env:WIX/bin" >> $GITHUB_PATH
      - run: echo "::set-output name=PATH::$GITHUB_PATH"

