name: Build-Windows-Static

on:
  push:
    branches:
      - release
    tags:
      - '*'
  pull_request:
    branches:
      - release
      - master
  workflow_dispatch:

jobs:
  build:
    name: Rust project
    runs-on: windows-latest
    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows-static
      VCPKG_ROOT: 'C:\vcpkg'
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@v2

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Setup vcpkg cache
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 64ca152891d6ab135c6c27881e7eb0ac2fa15bba

      - name: Setup vcpkg
        run: |
          (cargo install cargo-vcpkg || true)
          cargo vcpkg build

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Test
        uses: actions-rs/cargo@v1
        timeout-minutes: 10
        with:
          command: test
          args: --release --no-fail-fast -- --nocapture
      - uses: actions/upload-artifact@v2
        with:
          name: windows
          path: target/release/starsector_mod_manager.exe
