name: Build-Windows-Static-Debug

on:
  workflow_dispatch:

jobs:
  build:
    name: Rust project
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cache vcpkg installed
        uses: actions/cache@v1.0.3
        with:
          path: $VCPKG_ROOT/installed
          key: windows-vcpkg-cache
        env:
          VCPKG_ROOT: 'C:\vcpkg'
      - name: Cache vcpkg downloads
        uses: actions/cache@v1.0.3
        with:
          path: $VCPKG_ROOT/downloads
          key: windows-vcpkg-cache
        env:
          VCPKG_ROOT: 'C:\vcpkg'

      - name: Install dependencies Windows
        run: vcpkg integrate install; vcpkg install libarchive:x64-windows-static
        env:
          VCPKG_ROOT: 'C:\vcpkg'

      - name: Check cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
      - name: Test
        uses: actions-rs/cargo@v1
        timeout-minutes: 10
        with:
          command: test
          args: --release --no-fail-fast -- --nocapture
      - uses: actions/upload-artifact@v2
        with:
          name: windows
          path: target/release/moss.exe
